from NeuralNetwork import NeuralNetwork
import numpy as np

NN = NeuralNetwork(2)
NN.add_layer(2)
NN.add_layer(1)
INPUTS = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
OUTPUTS = np.array([[0], [0], [0], [1]])
print('UNTRAINED: ', NN.think(INPUTS[0]))
print('UNTRAINED: ', NN.think(INPUTS[1]))
print('UNTRAINED: ', NN.think(INPUTS[2]))
print('UNTRAINED: ', NN.think(INPUTS[3]))
NN.train(INPUTS, OUTPUTS, 50000)
print('1050: ', NN.think(INPUTS[0]))
print('1050: ', NN.think(INPUTS[1]))
print('1050: ', NN.think(INPUTS[2]))
print('1050: ', NN.think(INPUTS[3]))
print(NN)
#NN.propagate(INPUTS[2])
#print(NN)
#print(NN)